### ISSUE TITLE
bug(models): paths as model names render empty pages

### ISSUE THREAD

**Issue by grabbou** [rise-tools/rise-tools#111]
When you do as follows:
```ts
export const models = { delivery: A, 'delivery/form': B } 
```
it will render empty page.

CC: @ericvicenti

**Comment by ericvicenti** [comment]
hmm, I think this may be known behavior. The slash is used to drill into other models like if you have a lookup. The inventory example makes this clear. if you want slashes it would maybe work if you defined it like this

```
const models = {
  delivery: {
    '': A,
    form: B,
  }
}
```

**Comment by grabbou** [comment]
I am going to close this issue, because this is indeed expected behavior. Perhaps better logging would be advisable to make sure users don't end up accidentally doing that themselves.
