### ISSUE TITLE
Missing tamagui types on server components

### ISSUE THREAD

**Issue by bidah** [rise-tools/rise-tools#149]
Hey there 👋,

I was trying sample app and changing styles on `/src/example/navigation` and there where not types for the tamagui constructs such as Text. 

question aside is there a way to customize Tamagui with the [createThemeBuilder](https://tamagui.dev/docs/guides/theme-builder) API?

**Comment by grabbou** [comment]
Hey! Thanks for opening this issue! Are you on Discord server? There are few unanswered questions as far as configuring Tamagui and I would like to go over that with a few more people!

**Comment by ericvicenti** [comment]
Hey @bidah sorry for the slow response.

For types it seems like we have some bug that is not allowing the Tamagui types to go through. I'll try to look into this.

The tricky thing is we also should have runtime validation for types to make sure the server doesn't send invalid props. Usually I would use something like zod for this but that might not be the best choice for something as advanced as Tamagui.

For theming we support the <Theme> component, but we might need to do something more elaborate to support the createThemeBuilder API. I'm not sure the best steps there, your suggestions would be welcome!

And yes, we would love to see you on the RiseTools discord!

**Comment by grabbou** [comment]
Yeah, right now, you always end up with the default Tamagui theme (since that's what we pass to Provider that wraps Rise in the playground). However, if should have a way to customise it on per connection basis (e.g. you can return your own set of providers from the server, with custom values).

**Comment by grabbou** [comment]
> I was trying sample app and changing styles on /src/example/navigation and there where not types for the tamagui constructs such as Text.

@bidah as of 0.5.0 the types should be working just fine - please check the `package.json` and `tsconfig.json` of `template/blank-playground` (or start a new project with `npx create rise`). 

As far as your second comment:

> question aside is there a way to customize Tamagui with the [createThemeBuilder](https://tamagui.dev/docs/guides/theme-builder) API?

Like @ericvicenti said, we would love to support additional features and make it more flexible - best to open a dedicated issue or follow-up with us on Discord! You are more than welcome! We would love your input!

**Comment by bidah** [comment]
Thanks guys. Will try now and jump to the discord!
