### ISSUE TITLE
feat: release to Android and revamp meta 

### ISSUE THREAD

**Issue by grabbou** [rise-tools/rise-tools#42]
Screenshots, title and description were somewhat generated quickly to get the app out there as soon as possible. We should iterate and improve that relatively soon.

Also, we should release to Android Play Store now that our organisation has been verified.

Once completed, we should update the README to add nice HERO section pointing to App Store and Play Store.

**Comment by grabbou** [comment]
Also, need to release a new build to iOS that is CodePush-compatible, because previous builds didn't have it configured. Let's give Apple some time tho, since they "just" approved initial release!

**Comment by ericvicenti** [comment]
Ok, shipped to both app stores. Well done!!
