### ISSUE TITLE
dx: provide error message when passing mixed type as an array to function handler

### ISSUE THREAD

**Issue by grabbou** [rise-tools/rise-tools#72]
You can only do `event()`, `function` or `action` or `action[]`. If you mix multiple types in an array, this will not work and should be signalled to the user.

**Comment by TheKohan** [comment]
Hi, would happily start contributing here. Is this issue still up ? I've ran through the repo couple of times and I'm starting to get a hang of it (though everything is still foggy). Let me know if this is not to complex for a introductory PR.

**Comment by grabbou** [comment]
Hey, yes, I think this is good one. We already had something similar in the past, so searching the repository might help! Feel free to join our Discord server - https://discord.gg/khS5RYhS5K!

**Comment by grabbou** [comment]
Fixed in #124
